version: "3"

services:
  reblog:
    build:
      context: .
      args:
        - CNMIRROR=false
    volumes:
      - .:/reblog
    ports:
      - "3000:3000"
    depends_on:
      - db

  # TIP: 在生产构建中, CGO是关闭的, 请不要使用sqlite
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
