style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/redish101/reblog
options:
  tag_filter_pattern: "^v"
  sort: date
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - fix
      - chore
      - perf
      - refactor
      - docs
    title_maps:
      feat: 特性
      fix: 漏洞修复
      chore: 优化
      perf: 性能提升
      refactor: 代码重构
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s\\/]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
