basePath: /api
definitions:
  common.Resp:
    properties:
      data: {}
      msg:
        type: string
      success:
        type: boolean
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  handler.AdminLoginParams:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.AdminLoginResp:
    properties:
      token:
        type: string
    type: object
  handler.AdminSiteUpdateParams:
    properties:
      desc:
        type: string
      icon:
        type: string
      name:
        type: string
      url:
        type: string
    required:
    - desc
    - name
    - url
    type: object
  handler.AdminUserUpdateParams:
    properties:
      email:
        type: string
      nickname:
        maxLength: 32
        minLength: 2
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - email
    - nickname
    - password
    - username
    type: object
  handler.ArticleAddParams:
    properties:
      content:
        type: string
      desc:
        type: string
      draft:
        type: boolean
      slug:
        type: string
      title:
        type: string
    required:
    - content
    - desc
    - slug
    - title
    type: object
  handler.ArticleUpdateParams:
    properties:
      content:
        type: string
      desc:
        type: string
      draft:
        type: boolean
      slug:
        type: string
      title:
        type: string
    required:
    - content
    - desc
    - slug
    - title
    type: object
  handler.ArticlesListResp:
    properties:
      articles:
        items:
          $ref: '#/definitions/model.Article'
        type: array
      count:
        type: integer
    type: object
  handler.FriendAddParams:
    properties:
      avatar:
        type: string
      desc:
        maxLength: 256
        type: string
      name:
        maxLength: 32
        type: string
      url:
        type: string
    required:
    - avatar
    - name
    - url
    type: object
  handler.FriendListResp:
    properties:
      count:
        type: integer
      friends:
        items:
          $ref: '#/definitions/model.Friend'
        type: array
    type: object
  handler.FriendUpdateParams:
    properties:
      avatar:
        type: string
      desc:
        type: string
      name:
        type: string
      url:
        type: string
      visible:
        type: boolean
    type: object
  handler.InitParams:
    properties:
      desc:
        type: string
      email:
        type: string
      icon:
        type: string
      name:
        type: string
      nickname:
        type: string
      password:
        type: string
      url:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - nickname
    - password
    - url
    - username
    type: object
  handler.RespUserInfo:
    properties:
      nickname:
        type: string
      username:
        type: string
    type: object
  handler.RespVersion:
    properties:
      app_name:
        type: string
      commit:
        type: string
      runtime:
        type: string
      version:
        type: string
    type: object
  model.Article:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        type: string
      draft:
        type: boolean
      id:
        type: integer
      slug:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.Friend:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
      visible:
        type: boolean
    type: object
  model.Site:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  license:
    name: GPL-V3
  title: reblog api
  version: "1.0"
paths:
  /admin/login:
    post:
      description: 管理员使用用户名和密码进行登录，若登录成功，返回token
      parameters:
      - description: 登录凭据
        in: body
        name: adminLoginParams
        required: true
        schema:
          $ref: '#/definitions/handler.AdminLoginParams'
      responses:
        "200":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/handler.AdminLoginResp'
              type: object
        "400":
          description: 缺少必要参数
          schema:
            $ref: '#/definitions/common.Resp'
        "401":
          description: 用户名或密码错误
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 登录
      tags:
      - 站点管理
  /admin/site:
    put:
      description: 更新站点的名称、URL、描述和图标
      parameters:
      - description: 站点信息
        in: body
        name: adminSiteUpdateParams
        required: true
        schema:
          $ref: '#/definitions/handler.AdminSiteUpdateParams'
      responses:
        "200":
          description: 操作成功, 部分主题可能需重新部署生效
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 缺少参数
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 更新站点信息
      tags:
      - 站点管理
  /admin/tokenState:
    get:
      description: 获取当前token的状态
      responses:
        "200":
          description: 若值为true则token有效
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  type: boolean
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取token状态
      tags:
      - 站点管理
  /admin/userInfo:
    get:
      description: 获取管理员信息
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/handler.RespUserInfo'
              type: object
      summary: 获取管理员信息
      tags:
      - 站点管理
  /article/{slug}:
    delete:
      description: 根据slug删除文章
      parameters:
      - description: 文章的slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 缺少必要参数
          schema:
            $ref: '#/definitions/common.Resp'
        "404":
          description: 未知的文章
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 删除文章
      tags:
      - 文章
    get:
      description: 根据slug获取文章详情
      parameters:
      - description: 文章slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.Article'
              type: object
        "400":
          description: 缺少必要参数
          schema:
            $ref: '#/definitions/common.Resp'
        "404":
          description: 未知的slug
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 获取文章详情
      tags:
      - 文章
    post:
      description: 添加一篇新的文章
      parameters:
      - description: 文章slug
        in: path
        name: slug
        required: true
        type: string
      - description: 文章参数
        in: body
        name: articleAddParams
        required: true
        schema:
          $ref: '#/definitions/handler.ArticleAddParams'
      responses:
        "200":
          description: 操作成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 缺少必要参数
          schema:
            $ref: '#/definitions/common.Resp'
        "409":
          description: slug已被其他文章使用
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 添加文章
      tags:
      - 文章
    put:
      description: 根据slug更新文章的标题、描述和内容
      parameters:
      - description: 文章的slug
        in: path
        name: slug
        required: true
        type: string
      - description: 文章更新参数
        in: body
        name: articleUpdateParams
        required: true
        schema:
          $ref: '#/definitions/handler.ArticleUpdateParams'
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 缺失参数
          schema:
            $ref: '#/definitions/common.Resp'
        "404":
          description: 未知的文章
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 更新文章
      tags:
      - 文章
  /article/list:
    get:
      description: 分页获取文章列表
      parameters:
      - description: 页码, 默认为1
        in: query
        name: pageIndex
        type: integer
      - description: 每页数量, 默认为10
        in: query
        name: pageSize
        type: integer
      - description: 是否返回文章内容, 默认为false
        in: query
        name: content
        type: boolean
      responses:
        "200":
          description: 成功返回文章列表
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/handler.ArticlesListResp'
              type: object
        "400":
          description: 参数不合法
          schema:
            $ref: '#/definitions/common.Resp'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 分页获取文章列表
      tags:
      - 文章
  /friend:
    post:
      consumes:
      - application/json
      description: 添加友情链接
      parameters:
      - description: 友情链接信息
        in: body
        name: friendAddParams
        required: true
        schema:
          $ref: '#/definitions/handler.FriendAddParams'
      produces:
      - application/json
      responses:
        "200":
          description: 添加友情链接成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.Friend'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Resp'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 添加友情链接
      tags:
      - 友情链接
  /friend/{id}:
    delete:
      consumes:
      - application/json
      description: 根据ID删除一个已存在的友情链接
      parameters:
      - description: 友情链接的ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除友情链接成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 无效的ID格式
          schema:
            $ref: '#/definitions/common.Resp'
        "404":
          description: 链接不存在
          schema:
            $ref: '#/definitions/common.Resp'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 删除友情链接
      tags:
      - 友情链接
    put:
      consumes:
      - application/json
      description: 更新友情链接
      parameters:
      - description: 更新友情链接参数
        in: body
        name: friendUpdateParams
        required: true
        schema:
          $ref: '#/definitions/handler.FriendUpdateParams'
      produces:
      - application/json
      responses:
        "200":
          description: 更新友情链接成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Resp'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      security:
      - ApiKeyAuth: []
      summary: 更新友情链接
      tags:
      - 友情链接
  /friend/list:
    get:
      consumes:
      - application/json
      description: 分页获取友情链接, 若token有效则返回所有友情链接, 否则只返回可见的友情链接
      parameters:
      - description: 页码，默认为1
        in: query
        name: pageIndex
        type: integer
      - description: 每页大小，默认为10
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取友情链接成功
          schema:
            $ref: '#/definitions/handler.FriendListResp'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 获取友情链接
      tags:
      - 友情链接
  /init:
    post:
      consumes:
      - application/json
      description: 使用给定的参数初始化站点
      parameters:
      - description: 初始化参数
        in: body
        name: initParams
        required: true
        schema:
          $ref: '#/definitions/handler.InitParams'
      produces:
      - application/json
      responses:
        "200":
          description: 初始化成功
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: 无效的邮箱或URL
          schema:
            $ref: '#/definitions/common.Resp'
        "403":
          description: 此站点已初始化
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 初始化站点
      tags:
      - 站点管理
  /rss:
    get:
      description: 获取包含所有文章的Feed
      produces:
      - text/xml
      responses:
        "200":
          description: RSS Feed
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 获取Feed
      tags:
      - Feed
  /site:
    get:
      description: 获取站点信息
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.Site'
              type: object
      summary: 获取站点信息
      tags:
      - 站点
  /user/{username}:
    put:
      description: 管理员更新用户信息
      parameters:
      - description: 用户信息
        in: body
        name: adminUserUpdateParams
        required: true
        schema:
          $ref: '#/definitions/handler.AdminUserUpdateParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Resp'
      summary: 更新用户信息
      tags:
      - 站点管理
  /version:
    get:
      description: 获取reblog版本信息
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                data:
                  $ref: '#/definitions/handler.RespVersion'
              type: object
      summary: 获取reblog版本信息
      tags:
      - 版本
produces:
- application/json
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
